<a href="https://colab.research.google.com/github/kushkarki-okd/diseases_prediction/blob/main/diseases_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
from google.colab import drive

In [31]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
data=pd.read_csv('/content/drive/My Drive/data/syntheticdisease.csv')

In [33]:
data.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Hypothyroidism,loss_of_appetite,fatigue,cold_hands_and_feets,lethargy,mood_swings,weight_gain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alcoholic hepatitis,swelling_of_stomach,distention_of_abdomen,abdominal_pain,high_fever,headache,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Diabetes,restlessness,fatigue,lethargy,dizziness,weight_loss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Peptic ulcer disease,stomach_pain,indigestion,abdominal_pain,internal_itching,vomiting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hypoglycemia,vomiting,fatigue,anxiety,blurred_and_distorted_vision,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = data[col].str.strip()

In [35]:
symptoms_columns = [c for c in data.columns if c.startswith("Symptom_")]

all_symptoms = set()

for col in symptoms_columns:
    all_symptoms.update(data[col].dropna().unique())

all_symptoms = sorted(all_symptoms)

print("Total symptoms:", len(all_symptoms))

for s in all_symptoms:
    print(s)

Total symptoms: 101
abdominal_pain
acidity
altered_sensorium
anxiety
back_pain
blackheads
bladder_discomfort
blister
blood_in_sputum
bloody_stool
blurred_and_distorted_vision
breathlessness
bruising
burning_micturition
chest_pain
chills
cold_hands_and_feets
constipation
continuous_feel_of_urine
continuous_sneezing
cough
cramps
dark_urine
dehydration
diarrhoea
dischromic_patches
distention_of_abdomen
dizziness
excessive_hunger
extra_marital_contacts
family_history
fast_heart_rate
fatigue
foul_smell_of_urine
headache
high_blood_pressure
high_fever
hip_joint_pain
increased_appetite
indigestion
inflammatory_nails
internal_itching
irregular_sugar_level
irritation_in_anus
itching
joint_pain
knee_pain
lack_of_concentration
leg_pain
lethargy
loss_of_appetite
loss_of_balance
mood_swings
movement_stiffness
mucoid_sputum
muscle_wasting
muscle_weakness
nausea
neck_pain
nodal_skin_eruptions
obesity
pain_behind_the_eyes
pain_during_bowel_movements
pain_in_anal_region
painful_walking
patches_in_throat
phlegm
polyuria
prominent_veins
pus_filled_pimples
red_sore_around_nose
red_spots_over_body
redness_of_skin
restlessness
runny_nose
scaling
scarring
shivering
silver_like_dusting
skin_peeling
skin_rash
small_dents_in_nails
spinning_movements
spotting_urination
stiff_neck
stomach_pain
sunken_eyes
sweating
swelling_joints
swelling_of_stomach
swollen_legs
swollen_lymph_nodes
ulcers_on_tongue
vomiting
watering_from_eyes
weakness_in_limbs
weakness_of_one_body_side
weight_gain
weight_loss
yellow_crust_ooze
yellowish_skin

In [36]:

symptoms_columns = [
    c for c in data.columns
    if c.startswith("Symptom_")
]

all_symptoms = (
    pd.Series(data[symptoms_columns].values.ravel())
    .dropna()
    .unique()
)

all_symptoms = sorted(all_symptoms)




for symptom in all_symptoms:
    data[symptom] = (
        data[symptoms_columns]
        .eq(symptom)
        .any(axis=1)
        .astype(int)
    )


data = data[["Disease"] + all_symptoms]

/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (
/tmp/ipykernel_1866/2475020686.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[symptom] = (

In [37]:
data.head()

,Disease,abdominal_pain,acidity,altered_sensorium,anxiety,back_pain,blackheads,bladder_discomfort,blister,blood_in_sputum,...,swollen_lymph_nodes,ulcers_on_tongue,vomiting,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellowish_skin
0,Hypothyroidism,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,Alcoholic hepatitis,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Diabetes,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,Peptic ulcer disease,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Hypoglycemia,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [38]:
data.shape

(5000, 102)

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [40]:
x=data.drop("Disease",axis=1)
y=data["Disease"]

In [41]:
print("Data shape:", data.shape)

print("X shape:", x.shape)
print("Y shape:", y.shape)

print("X columns:", x.columns.tolist())

print("X empty:", x.empty)
print("Y empty:", y.empty)
print(data.columns.tolist())

Data shape: (5000, 102)
X shape: (5000, 101)
Y shape: (5000,)
X columns: ['abdominal_pain', 'acidity', 'altered_sensorium', 'anxiety', 'back_pain', 'blackheads', 'bladder_discomfort', 'blister', 'blood_in_sputum', 'bloody_stool', 'blurred_and_distorted_vision', 'breathlessness', 'bruising', 'burning_micturition', 'chest_pain', 'chills', 'cold_hands_and_feets', 'constipation', 'continuous_feel_of_urine', 'continuous_sneezing', 'cough', 'cramps', 'dark_urine', 'dehydration', 'diarrhoea', 'dischromic_patches', 'distention_of_abdomen', 'dizziness', 'excessive_hunger', 'extra_marital_contacts', 'family_history', 'fast_heart_rate', 'fatigue', 'foul_smell_of_urine', 'headache', 'high_blood_pressure', 'high_fever', 'hip_joint_pain', 'increased_appetite', 'indigestion', 'inflammatory_nails', 'internal_itching', 'irregular_sugar_level', 'irritation_in_anus', 'itching', 'joint_pain', 'knee_pain', 'lack_of_concentration', 'leg_pain', 'lethargy', 'loss_of_appetite', 'loss_of_balance', 'mood_swings', 'movement_stiffness', 'mucoid_sputum', 'muscle_wasting', 'muscle_weakness', 'nausea', 'neck_pain', 'nodal_skin_eruptions', 'obesity', 'pain_behind_the_eyes', 'pain_during_bowel_movements', 'pain_in_anal_region', 'painful_walking', 'patches_in_throat', 'phlegm', 'polyuria', 'prominent_veins', 'pus_filled_pimples', 'red_sore_around_nose', 'red_spots_over_body', 'redness_of_skin', 'restlessness', 'runny_nose', 'scaling', 'scarring', 'shivering', 'silver_like_dusting', 'skin_peeling', 'skin_rash', 'small_dents_in_nails', 'spinning_movements', 'spotting_urination', 'stiff_neck', 'stomach_pain', 'sunken_eyes', 'sweating', 'swelling_joints', 'swelling_of_stomach', 'swollen_legs', 'swollen_lymph_nodes', 'ulcers_on_tongue', 'vomiting', 'watering_from_eyes', 'weakness_in_limbs', 'weakness_of_one_body_side', 'weight_gain', 'weight_loss', 'yellow_crust_ooze', 'yellowish_skin']
X empty: False
Y empty: False
['Disease', 'abdominal_pain', 'acidity', 'altered_sensorium', 'anxiety', 'back_pain', 'blackheads', 'bladder_discomfort', 'blister', 'blood_in_sputum', 'bloody_stool', 'blurred_and_distorted_vision', 'breathlessness', 'bruising', 'burning_micturition', 'chest_pain', 'chills', 'cold_hands_and_feets', 'constipation', 'continuous_feel_of_urine', 'continuous_sneezing', 'cough', 'cramps', 'dark_urine', 'dehydration', 'diarrhoea', 'dischromic_patches', 'distention_of_abdomen', 'dizziness', 'excessive_hunger', 'extra_marital_contacts', 'family_history', 'fast_heart_rate', 'fatigue', 'foul_smell_of_urine', 'headache', 'high_blood_pressure', 'high_fever', 'hip_joint_pain', 'increased_appetite', 'indigestion', 'inflammatory_nails', 'internal_itching', 'irregular_sugar_level', 'irritation_in_anus', 'itching', 'joint_pain', 'knee_pain', 'lack_of_concentration', 'leg_pain', 'lethargy', 'loss_of_appetite', 'loss_of_balance', 'mood_swings', 'movement_stiffness', 'mucoid_sputum', 'muscle_wasting', 'muscle_weakness', 'nausea', 'neck_pain', 'nodal_skin_eruptions', 'obesity', 'pain_behind_the_eyes', 'pain_during_bowel_movements', 'pain_in_anal_region', 'painful_walking', 'patches_in_throat', 'phlegm', 'polyuria', 'prominent_veins', 'pus_filled_pimples', 'red_sore_around_nose', 'red_spots_over_body', 'redness_of_skin', 'restlessness', 'runny_nose', 'scaling', 'scarring', 'shivering', 'silver_like_dusting', 'skin_peeling', 'skin_rash', 'small_dents_in_nails', 'spinning_movements', 'spotting_urination', 'stiff_neck', 'stomach_pain', 'sunken_eyes', 'sweating', 'swelling_joints', 'swelling_of_stomach', 'swollen_legs', 'swollen_lymph_nodes', 'ulcers_on_tongue', 'vomiting', 'watering_from_eyes', 'weakness_in_limbs', 'weakness_of_one_body_side', 'weight_gain', 'weight_loss', 'yellow_crust_ooze', 'yellowish_skin']

In [42]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [43]:
model=LogisticRegression()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)

In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [47]:
accuracy_score(y_test,y_predict)
confusion_matrix(y_test,y_predict)

array([[23,  0,  0, ...,  0,  0,  0],
       [ 0, 26,  0, ...,  0,  0,  0],
       [ 0,  0, 21, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 23,  0,  0],
       [ 0,  0,  0, ...,  0, 19,  0],
       [ 0,  0,  0, ...,  0,  0, 13]])

In [50]:
print(classification_report(y_test,y_predict))

                              precision    recall  f1-score   support

                        AIDS       1.00      1.00      1.00        23
                        Acne       1.00      1.00      1.00        26
         Alcoholic hepatitis       0.95      1.00      0.98        21
                     Allergy       1.00      1.00      1.00        27
                   Arthritis       1.00      1.00      1.00        23
            Bronchial Asthma       1.00      1.00      1.00        28
        Cervical spondylosis       1.00      1.00      1.00        26
                 Chicken pox       1.00      0.94      0.97        18
         Chronic cholestasis       0.86      0.96      0.91        25
                 Common Cold       0.96      0.92      0.94        24
                      Dengue       0.91      0.94      0.92        32
                    Diabetes       1.00      1.00      1.00        24
Dimorphic hemorrhoids(piles)       1.00      1.00      1.00        24
               Drug Reaction       0.96      1.00      0.98        26
            Fungal infection       1.00      0.96      0.98        25
                        GERD       1.00      0.96      0.98        26
             Gastroenteritis       1.00      1.00      1.00        21
                Heart attack       0.96      1.00      0.98        22
                 Hepatitis B       1.00      0.95      0.97        20
                 Hepatitis C       0.57      0.60      0.59        20
                 Hepatitis D       0.61      0.74      0.67        19
                 Hepatitis E       0.48      0.65      0.55        17
                Hypertension       1.00      1.00      1.00        29
             Hyperthyroidism       1.00      1.00      1.00        22
                Hypoglycemia       1.00      1.00      1.00        37
              Hypothyroidism       1.00      1.00      1.00        21
                    Impetigo       1.00      1.00      1.00        19
                    Jaundice       1.00      0.83      0.91        30
              Kidney disease       1.00      0.95      0.98        22
                     Malaria       0.95      0.84      0.89        25
                    Migraine       1.00      1.00      1.00        27
              Osteoarthritis       1.00      1.00      1.00        24
Paralysis (brain hemorrhage)       1.00      0.85      0.92        26
        Peptic ulcer disease       1.00      1.00      1.00        25
                   Pneumonia       0.93      0.93      0.93        15
                   Psoriasis       1.00      1.00      1.00        25
                Tuberculosis       1.00      0.90      0.95        20
                     Typhoid       0.78      0.95      0.86        19
     Urinary tract infection       1.00      1.00      1.00        28
              Varicose veins       1.00      1.00      1.00        23
                     Vertigo       0.79      0.95      0.86        20
                 hepatitis A       0.65      0.50      0.57        26

                    accuracy                           0.94      1000
                   macro avg       0.94      0.94      0.94      1000
                weighted avg       0.95      0.94      0.94      1000